package scratch.model;

public enum ActionType {
    VAR_DECLARATION,
    VAR_ASSIGNMENT,
    INCREMENT_VARIABLE,
    MOVE_FORWARD,
    TURN_LEFT,
    TURN_RIGHT,
    REPEAT,
    END_REPEAT,
    PEN_UP,
    PEN_DOWN,
    DRAW_POLYGON,
    DRAW_RECTANGLE,
    TELEPORTATION,
    DRAW_CROSS
}